name: Deploy the code into Heroku

on: 
  push:
    branches:
      - maaster

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt install python3
    - name: push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:master 
